---
- name: default 
  box: centos/7
  cpus: 2
  memory: 4096 
  private_ip: 10.0.10.10
  package_manager: yum
  packages:
  - java
  - maven
  - git
  scripts:
  - nodejs
  - spring-petclinic-rest
  - spring-petclinic-angular
...

