---
- name: spring-petclinic 
  box: apline/apline64
  cpus: 2
  memory: 4096 
  private_ip: 10.0.10.10
  package_manager: apk
  packages:
  - docker
  scripts:
  - docker
  - docker_compose
  - spring_petclinic
...

